//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spetification
    {
        public int ID { get; set; }
        public int CountOfDoors { get; set; }
        public string VIN { get; set; }
        public int IDType { get; set; }
        public string IDCountry { get; set; }
        public byte[] Pic { get; set; }
        public int IDCar { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Country Country { get; set; }
        public virtual Type Type { get; set; }
    }
}
