//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computer
    {
        public int ID { get; set; }
        public string CPU { get; set; }
        public string GPU { get; set; }
        public string RAM { get; set; }
        public string MotherBoard { get; set; }
        public string HDD { get; set; }
        public string Keybourd { get; set; }
        public string Mouse { get; set; }
        public string Headphones { get; set; }
    }
}
